name: PRD-2-Modify manifest image

on:
  workflow_run:
    workflows: ["PRD-1-Generate images"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: Image tag (Commit)
        required: true

concurrency:
  group: prd-change-k8s-manifest
  cancel-in-progress: false

jobs:
  modify-manifest:
    if: ${{ github.event.workflow_run == null || (github.event.workflow_run != null && github.event.workflow_run.conclusion == 'success') }}

    permissions:
      contents: 'read'

    environment: prd

    name: Change image on k8s manifest
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Export image tag to Summary
        id: image-tag
        run: |
          IMAGE_TAG="${{ github.event.workflow_run.head_sha }}"
          if [ "${{ github.event.inputs.image-tag }}" != "" ]; then
            IMAGE_TAG="${{ github.event.inputs.image-tag }}"
          fi
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "### Image tag :framed_picture:" >> $GITHUB_STEP_SUMMARY
          echo "$IMAGE_TAG" >> $GITHUB_STEP_SUMMARY

      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: alnviana/poc-kubernetes-k8s-manifests
          token: ${{ secrets.CICD_GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "actions-bot@users.noreply.github.com"

      - name: Change image tag in the deployment.yaml
        run: |
          IMAGE="${{ vars.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.REPOSITORY_NAME }}/${{ vars.IMAGE_NAME_DEFAULT }}"
          IMAGE_TAG="${{ steps.image-tag.outputs.image-tag }}"
          yq e "(.spec.template.spec.containers[] | select(.name == \"${{ vars.APPLICATION_NAME }}\")).image = \"$IMAGE:$IMAGE_TAG\"" -i apps/${{ vars.APPLICATION_NAME }}/base/deployment.yaml
          git add apps/${{ vars.APPLICATION_NAME }}/base/deployment.yaml

      - name: Check the changes and commit
        run: |
          if git diff --staged --quiet; then
            echo "There are no changes to commit."
          else
            git commit -m "Automatic commit from the application repository"
            git push
            echo "Changes committed to the k8s manifest repository."
          fi
